name: dry-files
codacy_id: 71200ee8d70b412c9e21c20b8b3b3688
gemspec:
  authors: ["Luca Guidi"]
  email: ["me@lucaguidi.com"]
  summary: "file utilities"
  development_dependencies:
    - ['rake', '~> 13.0']
    - ['rspec', '~> 3.10']
    - ['rubocop', '~> 1.12']
